import { join } from 'node:path';
import { existsSync, readFileSync } from 'node:fs';
import {
  BaseAdapter,
  type AdapterContext,
  type AdapterResult,
  type ValidationResult,
} from './base.ts';

const CURSOR_DIR = '.cursor';
const RULES_FILE = 'rules';

export class CursorAdapter extends BaseAdapter {
  readonly name = 'cursor';
  readonly displayName = 'Cursor';
  readonly description = 'Generates .cursor/rules configuration for Cursor IDE';

  async generate(context: AdapterContext): Promise<AdapterResult> {
    const { skills, outputDir, dryRun = false } = context;
    const files: AdapterResult['files'] = [];
    const errors: string[] = [];

    try {
      const cursorDir = join(outputDir, CURSOR_DIR);
      const rulesPath = join(cursorDir, RULES_FILE);

      const existingRules = this.loadExistingRules(rulesPath);
      const skillsContent = this.buildRulesContent(skills);
      const finalContent = this.mergeRules(existingRules, skillsContent);

      if (finalContent.trim()) {
        const rulesFile = this.writeFile(rulesPath, finalContent, dryRun);
        files.push(rulesFile);
      }

      return { success: true, files, errors };
    } catch (error) {
      errors.push(error instanceof Error ? error.message : 'Unknown error');
      return { success: false, files, errors };
    }
  }

  override async validate(context: AdapterContext): Promise<ValidationResult> {
    const issues: ValidationResult['issues'] = [];

    for (const skill of context.skills) {
      if (!skill.name || skill.name.trim() === '') {
        issues.push({
          file: skill.filePath,
          message: 'Skill is missing a name',
          severity: 'error',
        });
      }

      if (!skill.content || skill.content.trim() === '') {
        issues.push({
          file: skill.filePath,
          message: 'Skill has no content',
          severity: 'warning',
        });
      }
    }

    return {
      valid: issues.filter((i) => i.severity === 'error').length === 0,
      issues,
    };
  }

  override async clean(context: AdapterContext): Promise<string[]> {
    const { outputDir, dryRun = false } = context;
    const cursorDir = join(outputDir, CURSOR_DIR);
    const deleted: string[] = [];

    const rulesPath = join(cursorDir, RULES_FILE);
    if (this.deleteFile(rulesPath, dryRun)) {
      deleted.push(rulesPath);
    }

    return deleted;
  }

  private loadExistingRules(rulesPath: string): string {
    if (!existsSync(rulesPath)) {
      return '';
    }

    try {
      const content = readFileSync(rulesPath, 'utf-8');
      const markerStart = '# === KIM QUY SKILLS START ===';
      const markerEnd = '# === KIM QUY SKILLS END ===';

      const startIdx = content.indexOf(markerStart);
      const endIdx = content.indexOf(markerEnd);

      if (startIdx !== -1 && endIdx !== -1) {
        const before = content.slice(0, startIdx).trim();
        const after = content.slice(endIdx + markerEnd.length).trim();
        return `${before}\n\n${after}`;
      }

      return content;
    } catch {
      return '';
    }
  }

  private buildRulesContent(skills: import('../core/skill/types.ts').Skill[]): string {
    if (skills.length === 0) {
      return '';
    }

    const lines: string[] = [
      '# === KIM QUY SKILLS START ===',
      '# Auto-generated by Kim Quy. Do not edit this section manually.',
      '',
    ];

    for (const skill of skills) {
      lines.push(`## ${skill.name}`);
      if (skill.description) {
        lines.push(`# ${skill.description}`);
      }
      lines.push('');
      lines.push(skill.content);
      lines.push('');
    }

    lines.push('# === KIM QUY SKILLS END ===');

    return lines.join('\n');
  }

  private mergeRules(existing: string, generated: string): string {
    const parts: string[] = [];

    if (existing.trim()) {
      parts.push(existing.trim());
    }

    if (generated.trim()) {
      parts.push(generated.trim());
    }

    return `${parts.join('\n\n')}\n`;
  }
}
